package toolcatalog

var builtinTagSpecs = map[string]BuiltinTagSpec{
	"archive":         {Description: "Archive search and transcript retrieval across past conversations."},
	"attachments":     {Description: "Attachment listing, search, and vision description tools."},
	"awareness":       {Description: "Watchlist and live-context entity management tools."},
	"contacts":        {Description: "Structured contact-directory records and vCard administration tools."},
	"development":     {Description: "Coarse entry point for software, repository, and code-change work. Usually leads to forge, files, web, or shell.", Menu: true},
	"diagnostics":     {Description: "Logs, usage, version, and operational debugging tools."},
	"documents":       {Description: "Indexed document-root browsing, search, and section retrieval tools."},
	"email":           {Description: "Email inbox reading, search, and sending tools."},
	"feeds":           {Description: "Media feed following and feed management tools."},
	"files":           {Description: "Workspace file read, write, edit, and search tools."},
	"forge":           {Description: "Forge and code-collaboration tools for issues, pull requests, checks, and reviews."},
	"ha":              {Description: "Home Assistant state, control, registry, and automation tools."},
	"home":            {Description: "Coarse entry point for home, device, room, and automation work. Usually leads to ha or notifications.", Menu: true},
	"homeassistant":   {Description: "Alias for ha: Home Assistant state, control, registry, and automation tools."},
	"interactive":     {Description: "Coarse entry point for interactive loop behavior and channel guidance. Usually leads to signal, owu, or owner context.", Menu: true},
	"knowledge":       {Description: "Coarse entry point for kb articles, memory, dossiers, and document understanding. Usually leads to documents, memory, files, or web.", Menu: true},
	"loops":           {Description: "Live loop status, sleep control, notifications, ad hoc spawn, and durable loop-definition authoring tools."},
	"media":           {Description: "Coarse entry point for transcripts, feeds, and media analysis. Usually leads to media, feeds, attachments, or web.", Menu: true},
	"memory":          {Description: "Persistent fact memory and working-memory tools."},
	"message_channel": {Description: "Current message-app conversation affordances, such as reactions, normalized across Signal, Matrix, iMessage, and similar providers."},
	"models":          {Description: "Model registry inspection, routing, and policy tools."},
	"mqtt":            {Description: "MQTT wake subscription management tools."},
	"notifications":   {Description: "Notification delivery, escalation, and actionable response tools."},
	"operations":      {Description: "Coarse entry point for routing, scheduling, logs, runtime state, and operational debugging. Usually leads to diagnostics, models, scheduler, loops, or companion.", Menu: true},
	"owner":           {Description: "Trusted owner/operator context set by runtime identity. When present, treat it as true; it can unlock owner-specific guidance and tools.", Menu: true, Protected: true},
	"owu":             {Description: "Open WebUI interactive chat loop context and guidance."},
	"people":          {Description: "Coarse entry point for identity, relationship context, and communication channels. Usually leads to person-record context, signal, email, or owner context.", Menu: true},
	"companion":       {Description: "Native companion app integration tools."},
	"scheduler":       {Description: "Scheduling and task management tools."},
	"web":             {Description: "Web page retrieval and wider-web discovery tools."},
	"session":         {Description: "Conversation/session lifecycle and checkpoint tools."},
	"shell":           {Description: "Shell execution tools for local command work."},
	"signal":          {Description: "Signal messaging tools."},
}
