package toolcatalog

var builtinTagSpecs = map[string]BuiltinTagSpec{
	"archive":       {Description: "Archive search and transcript retrieval across past conversations."},
	"attachments":   {Description: "Attachment listing, search, and vision description tools."},
	"awareness":     {Description: "Watchlist and live-context entity management tools."},
	"contacts":      {Description: "Contact storage, lookup, and vCard import/export tools."},
	"development":   {Description: "Coarse entry point for software, repository, and code-change work. Usually leads to forge, files, search, or shell.", Menu: true},
	"diagnostics":   {Description: "Logs, usage, version, and operational debugging tools."},
	"email":         {Description: "Email inbox reading, search, and sending tools."},
	"feeds":         {Description: "Media feed following and feed management tools."},
	"files":         {Description: "Workspace file read, write, edit, and search tools."},
	"forge":         {Description: "Forge and code-collaboration tools for issues, pull requests, checks, and reviews."},
	"ha":            {Description: "Home Assistant state, control, registry, and automation tools."},
	"home":          {Description: "Coarse entry point for home, device, room, and automation work. Usually leads to ha or notifications.", Menu: true},
	"homeassistant": {Description: "Alias for ha: Home Assistant state, control, registry, and automation tools."},
	"interactive":   {Description: "Coarse entry point for interactive loop behavior and channel guidance. Usually leads to signal, owu, or owner context.", Menu: true},
	"knowledge":     {Description: "Coarse entry point for kb articles, memory, dossiers, and document understanding. Usually leads to memory, files, or search.", Menu: true},
	"loops":         {Description: "Loop definition inspection, policy, and launch tools."},
	"media":         {Description: "Coarse entry point for transcripts, feeds, and media analysis. Usually leads to media, feeds, attachments, or search.", Menu: true},
	"memory":        {Description: "Persistent fact memory and working-memory tools."},
	"models":        {Description: "Model registry inspection, routing, and policy tools."},
	"mqtt":          {Description: "MQTT wake subscription management tools."},
	"notifications": {Description: "Notification delivery, escalation, and actionable response tools."},
	"operations":    {Description: "Coarse entry point for routing, scheduling, logs, platform state, and operational debugging. Usually leads to diagnostics, models, scheduler, loops, or platform.", Menu: true},
	"owner":         {Description: "Trusted owner/operator context set by runtime identity. When present, treat it as true; it can unlock owner-specific guidance and tools.", Menu: true, Protected: true},
	"owu":           {Description: "Open WebUI interactive chat loop context and guidance."},
	"people":        {Description: "Coarse entry point for contacts, relationships, and communication channels. Usually leads to contacts, signal, or owner context.", Menu: true},
	"platform":      {Description: "Native platform integration tools."},
	"scheduler":     {Description: "Scheduling and task management tools."},
	"search":        {Description: "Web search and web content retrieval tools."},
	"session":       {Description: "Conversation/session lifecycle and checkpoint tools."},
	"shell":         {Description: "Shell execution tools for local command work."},
	"signal":        {Description: "Signal messaging tools."},
}
