package toolcatalog

var builtinTagSpecs = map[string]BuiltinTagSpec{
	"archive":       {Description: "Archive search and transcript retrieval across past conversations."},
	"attachments":   {Description: "Attachment listing, search, and vision description tools."},
	"awareness":     {Description: "Watchlist and live-context entity management tools."},
	"contacts":      {Description: "Contact storage, lookup, and vCard import/export tools."},
	"diagnostics":   {Description: "Logs, usage, version, and operational debugging tools."},
	"email":         {Description: "Email inbox reading, search, and sending tools."},
	"feeds":         {Description: "Media feed following and feed management tools."},
	"files":         {Description: "Workspace file read, write, edit, and search tools."},
	"forge":         {Description: "Forge and code-collaboration tools for issues, pull requests, checks, and reviews."},
	"ha":            {Description: "Home Assistant state, control, registry, and automation tools."},
	"homeassistant": {Description: "Alias for ha: Home Assistant state, control, registry, and automation tools."},
	"interactive":   {Description: "Interactive chat loop context and guidance."},
	"loops":         {Description: "Loop definition inspection, policy, and launch tools."},
	"media":         {Description: "Media transcript and analysis tools."},
	"memory":        {Description: "Persistent fact memory and working-memory tools."},
	"models":        {Description: "Model registry inspection, routing, and policy tools."},
	"mqtt":          {Description: "MQTT wake subscription management tools."},
	"notifications": {Description: "Notification delivery, escalation, and actionable response tools."},
	"owner":         {Description: "Runtime-asserted owner/operator context and privileged tool gating.", Protected: true},
	"owu":           {Description: "Open WebUI interactive chat loop context and guidance."},
	"platform":      {Description: "Native platform integration tools."},
	"scheduler":     {Description: "Scheduling and task management tools."},
	"search":        {Description: "Web search and web content retrieval tools."},
	"session":       {Description: "Conversation/session lifecycle and checkpoint tools."},
	"shell":         {Description: "Shell execution tools for local command work."},
	"signal":        {Description: "Signal messaging tools."},
}
