package email

import (
	"context"
	"strings"
	"testing"

	"github.com/nugget/thane-ai-agent/internal/state/memory"
	"github.com/nugget/thane-ai-agent/internal/tools"
)

// TestPersonallyAddressedListReply pins the list-mail rule: in a turn
// the operator is not present for, a relaxed drafts-only account drafts
// a reply to bulk mail whose own To or Cc names the account's address,
// compared without case, with route personally_addressed_list_reply. It
// keeps refusing list mail that reached the account only through the
// list, anything auto_submitted, an owner-bound wake, and every strict
// or by_trust_zone account. The poster is a stranger, so the drafted
// rows also pin that the relaxed trust gate drafts the reply's
// recipient; an automated poster is still refused by the trust gate.
func TestPersonallyAddressedListReply(t *testing.T) {
	wake := func() context.Context {
		return tools.WithMessageOrigin(context.Background(), memory.OriginWake)
	}
	ownerWake := func() context.Context {
		ctx := tools.WithChannelBinding(context.Background(), &memory.ChannelBinding{Channel: "signal", Address: "+1", IsOwner: true})
		return tools.WithMessageOrigin(ctx, memory.OriginWake)
	}
	list := []string{"List-Id: Family <family.lists.example.net>", "Precedence: list"}
	listAutoGenerated := append([]string{"Auto-Submitted: auto-generated"}, list...)
	const (
		account  = "Thane <thane@example.com>"
		listAddr = "Family <family@lists.example.net>"
	)

	tests := []struct {
		name            string
		mode            gateMode
		ctx             func() context.Context
		from            string // the poster; Bob, a stranger, when empty
		to, cc          string
		headers         []string
		draft           bool
		wantDisposition Disposition
		wantRoute       string
		wantOriginal    HeaderMarks
		wantAttended    bool
		wantGap         string // a clause the refusal must carry
	}{
		{name: "list mail addressed to the account in to", mode: modeRelaxed, ctx: wake, to: account, headers: list,
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "list mail addressed to the account in cc, compared without case", mode: modeRelaxed, ctx: wake, to: listAddr, cc: "THANE@Example.COM", headers: list,
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "precedence bulk alone", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"Precedence: bulk"},
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "requested draft is still decided by the rule", mode: modeRelaxed, ctx: wake, to: account, headers: list, draft: true,
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "operator mailbox without smtp", mode: modeRelaxedNoSMTP, ctx: wake, to: account, headers: list,
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},

		{name: "addressed only through the list", mode: modeRelaxed, ctx: wake, to: listAddr, headers: list,
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true}, wantGap: "which this one does not"},
		{name: "auto_submitted list mail addressed to the account", mode: modeRelaxed, ctx: wake, to: account, headers: listAutoGenerated,
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{AutoSubmitted: AutoSubmittedGenerated, Bulk: true}, wantGap: "never for an automatic reply"},
		{name: "auto-reply addressed to the account", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"Auto-Submitted: auto-replied"},
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{AutoSubmitted: AutoSubmittedReplied}, wantGap: "never for an automatic reply"},
		{name: "Precedence junk alone, as classic auto-replies carry", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"Precedence: junk"},
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true, listReplyBar: listReplyBarJunk}, wantGap: "never for mail marked Precedence junk"},
		{name: "Precedence junk beside a List-Id still refuses", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"List-Id: Family <family.lists.example.net>", "Precedence: junk"},
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true, listReplyBar: listReplyBarJunk}, wantGap: "never for mail marked Precedence junk"},
		{name: "List-Unsubscribe alone is a sender's own mailing", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"List-Unsubscribe: <mailto:leave@example.net>"},
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true, listReplyBar: listReplyBarListFields}, wantGap: "only list marks are fields such as List-Unsubscribe"},
		{name: "List-Help alone is a sender's own mailing", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"List-Help: <mailto:help@example.net>"},
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true, listReplyBar: listReplyBarListFields}, wantGap: "only list marks are fields such as List-Unsubscribe"},
		{name: "List-Id beside List-Unsubscribe still drafts", mode: modeRelaxed, ctx: wake, to: account, headers: []string{"List-Id: Family <family.lists.example.net>", "List-Unsubscribe: <mailto:leave@example.net>"},
			wantDisposition: DispositionDrafted, wantRoute: RoutePersonallyAddressedListReply, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "owner-bound wake is unattended", mode: modeRelaxed, ctx: ownerWake, to: listAddr, headers: list,
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true}, wantGap: "which this one does not"},
		{name: "automated poster stays refused by the trust gate", mode: modeRelaxed, ctx: wake, from: "Alerts <noreply@example.com>", to: account, headers: list,
			wantDisposition: DispositionRefused, wantRoute: RouteTrustGate, wantOriginal: HeaderMarks{Bulk: true}},

		{name: "strict drafts account", mode: modeStrict, ctx: wake, to: account, headers: list,
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true}},
		{name: "by_trust_zone account", mode: modeByTrustZone, ctx: wake, to: account, headers: list,
			wantDisposition: DispositionRefused, wantRoute: RouteAutomaticResponse, wantOriginal: HeaderMarks{Bulk: true}},

		{name: "control: attended list-only reply drafts by policy", mode: modeRelaxed, ctx: attendedCtx, to: listAddr, headers: list,
			wantDisposition: DispositionDrafted, wantRoute: RoutePolicyDrafts, wantOriginal: HeaderMarks{Bulk: true}, wantAttended: true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			svc, mem, smtp := gateService(t, tt.mode, nil)
			headers := tt.headers
			if tt.cc != "" {
				headers = append([]string{"Cc: " + tt.cc}, headers...)
			}
			from := tt.from
			if from == "" {
				from = "Bob <bob@example.net>"
			}
			uid := mem.append("INBOX", rawMessage(from, tt.to, "Reunion", "who is coming?", headers...))
			args := map[string]any{"uid": float64(uid), "body": "we are"}
			if tt.draft {
				args["draft"] = true
			}
			out, err := svc.ToolProvider().HandleReply(tt.ctx(), args)

			var decision Decision
			if tt.wantDisposition == DispositionRefused {
				refusal := refusalOf(t, err)
				decision = refusal.Decision
				if tt.wantRoute == RouteAutomaticResponse {
					if sentence, _, _ := strings.Cut(err.Error(), "\n"); !strings.HasSuffix(sentence, ".") || strings.Contains(sentence, ". ") {
						t.Errorf("refusal reason must be one sentence: %q", sentence)
					}
					if tt.wantGap != "" {
						mustContain(t, refusal.Message, tt.wantGap)
					} else if strings.Contains(refusal.Message, "drafts-only account") {
						t.Errorf("an account without the rule must not describe it: %s", refusal.Message)
					}
				}
			} else {
				if err != nil {
					t.Fatalf("want %s, got %v", tt.wantDisposition, err)
				}
				decision = decodeSend(t, out).Decision
			}
			if decision.Disposition != tt.wantDisposition || decision.Route != tt.wantRoute || decision.Original != tt.wantOriginal || decision.Attended != tt.wantAttended {
				t.Errorf("decision = %s route %s original %+v attended %v, want %s route %s original %+v attended %v",
					decision.Disposition, decision.Route, decision.Original, decision.Attended, tt.wantDisposition, tt.wantRoute, tt.wantOriginal, tt.wantAttended)
			}

			wantDrafts := 0
			if tt.wantDisposition == DispositionDrafted {
				wantDrafts = 1
			}
			if n := len(smtp.received()); n != 0 {
				t.Errorf("SMTP deliveries = %d; this rule never sends", n)
			}
			acct, _ := svc.ResolveAccount(context.Background(), "primary")
			drafts, err := acct.Client.ListMessages(context.Background(), ListOptions{Folder: "Drafts"})
			if err != nil {
				t.Fatalf("list drafts: %v", err)
			}
			if n := len(drafts.Envelopes); n != wantDrafts {
				t.Errorf("drafts = %d, want %d", n, wantDrafts)
			}
		})
	}
}
