# Build configuration for Home Assistant Add-on
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-build-configuration

build_from:
  aarch64: golang:1.23-alpine
  amd64: golang:1.23-alpine
  armv7: golang:1.23-alpine

args:
  BUILD_ARCH: ${BUILD_ARCH}
